micronaut:
  application:
    name: videoMicroservice
  server:
    port: 8080
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://${DB_HOST:`localhost:3306`}/${DB_NAME:videos}
    username: ${DB_USER:todo}
    password: ${DB_PASSWORD:todosecret}
jpa:
  default:
    entity-scan:
       packages:
          - com.video.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
    bootstrap:
        servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}
netty:
  default:
    allocator:
      max-order: 3
